### ISSUE TITLE
Avoid "named" returns (in long functions)

### ISSUE THREAD

**Issue by ethers** [0xProject/contracts#104]
For example, replacing the named return [`returns(uint filledTakerTokenAmount)`](https://github.com/0xProject/contracts/blob/888d5a02573572240f4c55e03238be603c13c469/contracts/Exchange.sol#L109) with `returns (uint)` and explicitly declaring https://github.com/0xProject/contracts/blob/888d5a02573572240f4c55e03238be603c13c469/contracts/Exchange.sol#L140
with `uint filledTakerTokenAmount`... would make the code more clear, explicit, and less prone to bugs getting introduced (for example, if return was used instead of return 0 in that function). (The gas saving is also quite trivial.)

Some other info on "named" returns: https://github.com/ethereum/solidity/issues/1401

They are likely safer if a function is very simple like https://github.com/0xProject/contracts/blob/888d5a02573572240f4c55e03238be603c13c469/contracts/Exchange.sol#L572 but arguably its documentation benefit is moot.
(There's more to "named" returns such as https://github.com/ethereum/solidity/issues/1141 and we'd want code safety first.)

**Comment by abandeali1** [comment]
The example you provided is unfortunately the one place we can't remove the named return, due to running against the local variable limit (the named return take up one less slot in this case).
