### ISSUE TITLE
TokenDistributionWithRegistry.sol does not reference the Registry

### ISSUE THREAD

**Issue by maurelian** [0xProject/contracts#106]
Despite the name, [TokenDistributionWithRegistry](https://github.com/0xProject/contracts/blob/frozen/contracts/TokenDistributionWithRegistry.sol) contract does not import, or make any reference to the Registry contract at all. This is confusing.

**Comment by abandeali1** [comment]
TokenDistributionWithWhitelist, perhaps?

**Comment by maurelian** [comment]
Oh, is registry/whitelist meant to refer to the `registered` mapping? I had assumed it was the [TokenRegistry](https://github.com/0xProject/contracts/blob/frozen/contracts/TokenRegistry.sol)

**Comment by abandeali1** [comment]
Yep, I could see how that is confusing though.

**Comment by abandeali1** [comment]
`TokenSale` by itself is probably most clear, actually.
