### ISSUE TITLE
`isTransferable()` function should be removed

### ISSUE THREAD

**Issue by GNSPS** [0xProject/contracts#107]
The `isTransferable()` function, referenced in:
https://github.com/0xProject/contracts/blob/master/contracts/Exchange.sol#L151
should be removed.

It does not only represent a repetition of checks against a benign (or malicious) ERC20 token and hence wasting gas (*claim 1*) but also an unnecessarily added reentrancy point (*claim 2*).

About *claim 1*:
* The function checks assume the contract's state stays intact throughout multiple calls which, by ERC20 specs, should, but in a malicious token shouldn't. (https://github.com/0xProject/contracts/blob/master/contracts/Exchange.sol#L556)
* Referring back to the point above, if the assumption about the token contract being benign is already made why check the balance again in `isTransferable()` when the same check is already made inside the ERC20 token contract? (gas is already wasted for that!)

About *claim 2*:
I couldn't, to the extent of my analyzing and testing skills, find any reentrancy *bug* but if there's any lesson *theDao* has taught us is that **accessing/changing state variables *after* an external call  in a function is not only dangerous but should be avoided at all costs**.

Such is the case on https://github.com/0xProject/contracts/blob/master/contracts/Exchange.sol#L151 as, following the external calls in `isTransferable()`, `filled[order.orderHash]` is accessed in https://github.com/0xProject/contracts/blob/master/contracts/Exchange.sol#L159.

While it doesn't represent a *bug* in itself it is a poor design choice. Any specific reason to have this check before accessing the mapping?

**Recommendation**:

If the only purpose of this check is, as seems, firing that specific event then I would propose firing that same event after checking the return boolean from the successive `transferViaProxy()` calls (https://github.com/0xProject/contracts/blob/master/contracts/Exchange.sol#L166) which represent the only call needed to check the conditions needed to fill the order.

I can only imagine the suppression of this function in such a widely used function as `fillOrder()` would represent huge gas savings.

This would also entail ditching the use of the `assert` construct which is itself wasting gas (after the `REVERT` opcode is indeed activated) and favor an `if() { Event(); revert(); }` pattern like is now present in the original check.

Or in an alternative solution have the contract call the `isTransferable()` function with a low-level Solidity `call()` function so as to not have subsequent `fillOrder()` calls interrupting a batched number of orders with bubbling up `throw`s.

**Comment by abandeali1** [comment]
The main purpose of `isTransferable` is to make fills fail softly, so that a single failure does cause an entire `batchFillOrders` call to fail. I agree it isn't particularly clean or gas efficient, but it is optional.

It does add extra reentrancy risk. We will be pushing a change soon that forwards limited gas to `getBalance` and `getAllowance` calls, which should eliminate this completely.
