### ISSUE TITLE
TokenRegistry contract can override past token metadata silently

### ISSUE THREAD

**Issue by GNSPS** [0xProject/contracts#115]
In the _TokenRegistry_ contract neither the `addToken()`, `setTokenName()` or the `setTokenSymbol()` check for overwrites in both the `tokenByName` or `tokenBySymbol` mappings.

Although the contract in question is supposed to be controlled only by the DAO/MultiSig, as per the specs, this lack of checks could result in some major confusion in the use of the 0x UI.

Not to mention that assuming a flaw or compromised future DAO it could lead to some severe social engineering attacks.

**Recommendation**:
Implement a simple `require()` statement to check if the mapping key being added is already set.

**Comment by abandeali1** [comment]
Good catch!
