### ISSUE TITLE
Redundant check on `getEthCapPerAddress()` function

### ISSUE THREAD

**Issue by GNSPS** [0xProject/contracts#142]
The `startTimeInSec == 0` part of the condition check at https://github.com/0xProject/contracts/blob/frozenUpdated/contracts/TokenSale.sol#L229 is redundant given `startTimeInSec` can only be set in `initializeSale()` which itself has the `validStartTime(_startTimeInSec)` modifier meaning that the value passed to init the state variable cannot be zero.

**Recommendation**

Remove that part of the conditional check.

**Comment by abandeali1** [comment]
This check is in place so that `getEthCapPerAddress` returns `0` when called before the sale is initialized (otherwise `2 ** currentPeriod` is larger than `2 ** 256`).

**Comment by GNSPS** [comment]
Totally missed that @abandeali1, don't know why I assumed that function was the constructor! 😄
