### ISSUE TITLE
TokenDistributionWithRegistry::init does not ensure zero fees

### ISSUE THREAD

**Issue by maurelian** [0xProject/contracts#144]
* `TokenDistributionWithRegistry::init()` has no `require` or `assert` statement to ensure that there are no fees, and no `feeRecipient` specified on the order. This can only be verified by viewing the contract's storage after the order has been created. This is particularly relevant given that the `TokenDistributionWithRegistry` contract uses the Exchange mechanism, but inserts itself as the taker, and then forwards the proceeds to the caller of `fillOrderWithEth()`.

**Recommendation**

Add a `require` statement ensuring no extra fees will be paid on order fills.

There is already a check that `require(order.feeRecipient == address(0));`, adding `require(order.takerFee == 0 && order.makerFee == 0 )` would reduce the need to verify the deployment.

**Comment by abandeali1** [comment]
The `fillOrder` function doesn't transfer fees if `order.feeRecipient` is a null address. So `require(order.feeRecipient == address(0))` should be sufficient to guarantee the order has no fees.

**Comment by maurelian** [comment]
Right, thanks for clarifying.
