### ISSUE TITLE
Paying less fees by taking advantage of rounding errors

### ISSUE THREAD

**Issue by AlexXiong97** [0xProject/contracts#157]
Another concern consequentially derived from rounding error is a strategy takers may take advantage of to minimize the transaction fees he/she pays. Specifically `paidTakerFee` is calculated using `getPartialAmount` function which truncates the decimal. First of all, `fillOrder()` doesn't check the error percentage to make sure it was below 0.1%. Secondly, even if it does, takers could still try to construct his order into smaller chunks to "enjoy a 0.1% discount" in every chunk. Thirdly, since relayer will most likely pick orders with high transaction fees, makers could claim to pay a slightly higher fee in the order while in fact they're not, to get a prioritized inclusion onto the order book. 

===========================================
For the first point, a new PR #156  has been created as a solution. PR #158 is corresponding tests. 
This point has been added to ConsenSys Diligence report:
https://github.com/ConsenSys/0x_review/blob/wip/report/3_general_findings.md#paying-less-fees-by-taking-advantage-of-rounding-errors

**Comment by abandeali1** [comment]
Since ZRX has 18 decimal places, this will never be an issue in practice (it will cost a lot more in gas to than the amount saved by creating a rounding error).
