### ISSUE TITLE
Order salts don't support the full range of UINT_256

### ISSUE THREAD

**Issue by tommy-a** [0xProject/contracts#161]
https://github.com/0xProject/contracts/blob/70454b2218eb2486b5f8584f338afad7b9564f02/util/order_factory.ts#L25

Given a MAX_UINT value of 999 (indulge me for the purpose of this example)
- `MAX_DIGITS_IN_UNSIGNED_256_INT` = 3

`BigNumber.random(3)` will yield at max 0.999, hence a scenario of:
- max `randomNumber` = 0.999
- max `factor` = 10 ** (3 - 1) = 10 ** 2 = 100
- max `salt` = (0.999 * 100).round() = (99.9).round() = 100

Why not just multiply by `MAX_DIGITS_IN_UNSIGNED_256_INT` and not round (?):
- max `randomNumber` = 0.999
- max `factor` = 10 ** (3 - 0) = 10 ** 3 = 1000
- max `salt` = (0.999 * 1000) = 999 (<-- yay!)

**Comment by abandeali1** [comment]
Good catch, though this is probably more important in the 0x.js repo. I'll make the change. 
https://github.com/0xProject/0x.js/blob/89aa19f6e4042ffcda906e4fa6a7de3d6d2e57c1/src/0x.ts#L96

**Comment by tommy-a** [comment]
Although on second thought, while this solution does give the max range, it also results in overflow, so you wouldn't get a normal distribution from 0 -> `MAX_UNIT_256`.  I believe you'd want something like:

(where `MAX_UINT_256` is the max value that the uint256 type can take)

``` js
function generateSalt() {
  return BigNumber.random(MAX_DIGITS_IN_UNSIGNED_256_INT) * (MAX_UINT_256 + 1);
}
```

**Comment by tommy-a** [comment]
Not to be a dick, but yall have many issues similar to this scattered throughout your codebase.  You should really focus on quality moving forward.

**Comment by abandeali1** [comment]
This repo's tests/utils will be undergoing a heavy refactor soon. In the meantime, please feel free to point out said issues.

**Comment by tommy-a** [comment]
I most certainly would if I believed in the longevity of this project, but I'm of the opinion that you've (org-wise) consistently mis-understood the potential of what you've released.  Congrats on the ICO though

**Comment by abandeali1** [comment]
Thank you for the constructive feedback.

**Comment by tommy-a** [comment]
But of course
