### ISSUE TITLE
Don't use exchange for crowdsale.

### ISSUE THREAD

**Issue by MicahZoltu** [0xProject/contracts#72]
The exchange code is largely not battle tested and it is completely unnecessary for the crowdsale as all token purchases are between the crowdsale contract and the ICO buyer.  Rather than introducing additional risk into the crowdsale, use a much simpler contract that isn't built on top of relatively new code (like the exchange).

In this case, it feels like the exchange is being used as a sort mechanism for proving you can rather than because it is necessary or beneficial.  The exception to this would be if you plan on running the crowdsale off-chain by sending pre-registered users orders that they can then settle on-chain at their convenience.  However, looking at the contract this does _not_ appear to be what is happening (based on the fact that people can send ETH to the contract directly and have it complete a sale).

It is also possible that `SimpleCrowdsale.sol` is not the crowdsale you will be running but instead meant as an example crowdsale that uses 0x of some kind.  If that is the case then I recommend removing the catch all function and having the crowdsale _actually_ leverage 0x in a meaningful way as that will make for a much better example.

**Comment by LogvinovLeon** [comment]
The Exchange code (as well as all other smart contracts) would be audited before the crowdsale by multiple independent auditors.

**Comment by MicahZoltu** [comment]
Auditors don't catch everything. Adding unnecessary code increases risk (unnecessarily).  Auditors decrease risk.  No matter how much auditing you do you can't reduce risk to zero (think of auditing as a percentage risk reduction).  The best you can do is mitigate risks in any way you can.  One way is via audits, and another is to remove superfluous code.
