### ISSUE TITLE
Merge filled and cancelled.

### ISSUE THREAD

**Issue by MicahZoltu** [0xProject/contracts#74]
I could be overlooking something, but it seems like one could make it so cancelling (or partially cancelling) an order simply fills by that amount.  At the moment fill and cancel are separate state variables that effectively fill the same role (which is to track how much of an order is remaining).  If there is no functional difference between cancelling some portion of an order and filling some portion of an order aside from the actual value transfers that occur during that process, then I think these two things should be reduced into a single state variable.

This will simplify the code in a few places (no longer need to sum the two values) and would reduce overall gas costs since there would only be one state variable being updated instead of two.

**Comment by abandeali1** [comment]
We originally had it that way, but I think it is useful to have on-chain proof that an order was either filled or cancelled (it was impossible to differentiate before). 

I think the main argument for combining them is that it's 15K gas cheaper (one time) to fill/cancel an order after it has already been partially filled/cancelled.

**Comment by MicahZoltu** [comment]
Why does one need to tell the difference between a cancel and a fill _on-chain_?  You can log cancel vs fill as an event so people can identify the difference off-chain, but it is unclear to me why you would need this information on-chain for anything.

I think the gas costs are secondary to reducing code complexity.  In this case, I'm struggling to understand the benefit of having them separate, and the separation increases risk.

**Comment by abandeali1** [comment]
An order being filled means that value was actually transferred and that fees were paid. I can see this being useful in a fee splitting contract or in a DAO, just to name a few examples. 

Separating `filled` and `cancelled` is a small tweak that can allow for some pretty cool systems of smart contracts to incorporate 0x.
