### ISSUE TITLE
ipfshash assumptions

### ISSUE THREAD

**Issue by ethers** [0xProject/contracts#75]
TokenRegistry assumes `bytes32` for ipfshash
https://github.com/0xProject/contracts/blob/888d5a02573572240f4c55e03238be603c13c469/contracts/TokenRegistry.sol#L94

An ipfshash is a https://github.com/multiformats/multihash and the TokenRegistry might also be assuming a convention that the first 2 bytes of the ipfshash, which are not stored on-chain are 0x1220.

Assumptions and guidance should be documented, and/or possibly future-proofing by using `bytes` type instead.

**Comment by abandeali1** [comment]
Good catch, it seems like a dynamic byte array is our best option given that there's a chance this may change in the future.

I wonder if we should do the same for `swarmHash` for the sake of future proofing as well.

**Comment by maurelian** [comment]
Possibly useful:
https://www.reddit.com/r/ethdev/comments/6lbmhy/a_practical_guide_to_cheap_ipfs_hash_storage_in/

See the comments there as well. Myself, I have not thought deeply about the best approach.
