### ISSUE TITLE
`changeRegistrationStatus` should have `distributionNotInitialized` modifier on it.

### ISSUE THREAD

**Issue by MicahZoltu** [0xProject/contracts#82]
Smart contracts should not rely on users implicitly trusting the smart contract's author to "do the right thing".  In that vein, the 0x team should not be trusted to not call `changeRegistrationStatus` once the ICO has started, so it should have the `distributionNotInitialized` modifier on it to prevent late-game changes.

**Comment by abandeali1** [comment]
That's fair, I'll make the change.
