### ISSUE TITLE
setCapPerAddress can be changed by the owner at any time

### ISSUE THREAD

**Issue by ethers** [0xProject/contracts#84]
https://github.com/0xProject/contracts/blob/888d5a02573572240f4c55e03238be603c13c469/contracts/TokenDistributionWithRegistry.sol#L224-L225

As there is no specification, it's not clear whether this is intended behavior. In past token sales, typically there are restrictions in code on when terms of the sale can be modified: for example, an obvious one would be to not allow the capPerAddress to be changed by anyone once the sale has started.

**Comment by abandeali1** [comment]
This is intentional. It allows us to guarantee participation of registered addresses by breaking up the distribution into multiple rounds.
