### ISSUE TITLE
Scalability redesign in the MultiSigWalletWithTimeLockExceptRemoveAuthorizedAddress contract

### ISSUE THREAD

**Issue by GNSPS** [0xProject/contracts#94]
This contract does several things not as efficiently as expected. 

Some of which are almost an anti-pattern like is the case in https://github.com/0xProject/contracts/blob/master/contracts/MultiSigWalletWithTimeLockExceptRemoveAuthorizedAddress.sol#L12 which is `assert`ing a custom function which itself `assert`s a byte-by-byte comparison of a tightly packed `bytes` array vs. a `bytes4` type signature.

Will submit a PR with a recommendation for a much cheaper and scalable design.

**Comment by abandeali1** [comment]
After internal discussions, we have decided to go for code clarity over efficiency in this case. `isFunctionRemoveAuthorizedAddress` will most likely be only called once in the contract's lifetime, so efficiency isn't particularly important.
