### ISSUE TITLE
`makerFee` and `takerFee` fields are not included in the white paper for point to point orders

### ISSUE THREAD

**Issue by ethers** [0xProject/contracts#97]
`makerFee` and `takerFee` fields are not included in the white paper for point to point orders.
#91 suggests that they should be added to the white paper for point to point orders.

**Comment by abandeali1** [comment]
There have been some changes to the protocol since the release of the whitepaper, most notably the addition of a salt to the order format and the combination of point to point/broadcast orders. The whitepaper will definitely be updated at some point.
